import 'package:myapp/entites/course.dart';

class Electrical {

  
  final List<Course> generalCoursesList = [
    Course(
      name: "Computer Skills",
      code: "CSC 001",
      creditHours: 0,
      gpa: 0,
      gpaLetter: 'NF',
    ),
    Course(
      name: "Communication & Presentation Skills",
      code: "HUM 108",
      creditHours: 2,
      gpa: 0,
      gpaLetter: 'NF',
    ),
    Course(
      name: "Analysis & Research Skills",
      code: "HUM 109",
      creditHours: 2,
      gpa: 0,
      gpaLetter: 'NF',
    ),
    Course(
      name: "Principles of Negotiation",
      code: "HUM 204",
      creditHours: 2,
      gpa: 0,
      gpaLetter: 'NF',
    ),
    Course(
      name: "Human Rights",
      code: "HUM 205",
      creditHours: 1,
      gpa: 0,
      gpaLetter: 'NF',
    ),
    Course(
      name: "English Language (1)",
      code: "LNG 001",
      creditHours: 2,
      gpa: 0,
      gpaLetter: 'NF',
    ),
    Course(
      name: "English Language (2)",
      code: "LNG 002",
      creditHours: 2,
      gpa: 0,
      gpaLetter: 'NF',
    ),
    Course(
      name: "Arabic Language",
      code: "LNG 003",
      creditHours: 2,
      gpa: 0,
      gpaLetter: 'NF',
    ),
    Course(
      name: "Physical Education & Activities (1)",
      code: "PHE 001",
      creditHours: 0,
      gpa: 0,
      gpaLetter: 'NF',
    ),
    Course(
      name: "Physical Education & Activities (2)",
      code: "PHE 101",
      creditHours: 0,
      gpa: 0,
      gpaLetter: 'NF',
    ),
    Course(
      name: "Physical Education & Activities (3)",
      code: "PHE 201",
      creditHours: 1,
      gpa: 0,
      gpaLetter: 'NF',
    ),
    Course(
      name: "Introduction to Field Training",
      code: "FTR 031",
      creditHours: 3,
      gpa: 0,
      gpaLetter: 'NF',
    ),
  ];

  final List<Course> requirementCoursesList = [
    Course(
      name: "Field Training (1)",
      code: "FTR 131",
      creditHours: 3,
      gpa: 0,
      gpaLetter: 'NF',
    ),
    Course(
      name: "Field Training (2)",
      code: "FTR 161",
      creditHours: 3,
      gpa: 0,
      gpaLetter: 'NF',
    ),
    Course(
      name: "Mathematics (1)",
      code: "MTH 001",
      creditHours: 3,
      gpa: 0,
      gpaLetter: 'NF',
    ),
    Course(
      name: "Mathematics (2)",
      code: "MTH 002",
      creditHours: 3,
      gpa: 0,
      gpaLetter: 'NF',
    ),
    Course(
      name: "Statistics & Probability Theory",
      code: "MTH 105",
      creditHours: 3,
      gpa: 0,
      gpaLetter: 'NF',
    ),
    Course(
      name: "Physics (1)",
      code: "PHY 001",
      creditHours: 3,
      gpa: 0,
      gpaLetter: 'NF',
    ),
    Course(
      name: "Physics (2)",
      code: "PHY 002",
      creditHours: 3,
      gpa: 0,
      gpaLetter: 'NF',
    ),
    Course(
      name: "Engineering Mechanics (1)",
      code: "ENG 001",
      creditHours: 2,
      gpa: 0,
      gpaLetter: 'NF',
    ),
    Course(
      name: "Engineering Mechanics (2)",
      code: "ENG 002",
      creditHours: 2,
      gpa: 0,
      gpaLetter: 'NF',
    ),
    Course(
      name: "Engineering Chemistry",
      code: "CHM 001",
      creditHours: 3,
      gpa: 0,
      gpaLetter: 'NF',
    ),
    Course(
      name: "Environmental Impact of Projects",
      code: "MNG 202",
      creditHours: 1,
      gpa: 0,
      gpaLetter: 'NF',
    ),
    Course(
      name: "Engineering Drawing & Projection (1)",
      code: "ENG 003",
      creditHours: 2,
      gpa: 0,
      gpaLetter: 'NF',
    ),
    Course(
      name: "Engineering Drawing & Projection (2)",
      code: "ENG 004",
      creditHours: 2,
      gpa: 0,
      gpaLetter: 'NF',
    ),
    Course(
      name: "History of Engineering & Technology",
      code: "ENG 006",
      creditHours: 1,
      gpa: 0,
      gpaLetter: 'NF',
    ),
    Course(
      name: "Principles of Production Technology & Workshop",
      code: "ENG 005",
      creditHours: 3,
      gpa: 0,
      gpaLetter: 'NF',
    ),
    Course(
      name: "Project Management",
      code: "MNG 201",
      creditHours: 2,
      gpa: 0,
      gpaLetter: 'NF',
    ),
    Course(
      name: "Monitoring & Quality Control Systems",
      code: "MNG 101",
      creditHours: 1,
      gpa: 0,
      gpaLetter: 'NF',
    ),
    Course(
      name: "Engineering Economics",
      code: "MNG 102",
      creditHours: 2,
      gpa: 0,
      gpaLetter: 'NF',
    ),
    Course(
      name: "Technical Report Writing",
      code: "MNG 103",
      creditHours: 2,
      gpa: 0,
      gpaLetter: 'NF',
    ),
    Course(
      name: "Professional Ethics",
      code: "MNG 203",
      creditHours: 1,
      gpa: 0,
      gpaLetter: 'NF',
    ),
    Course(
      name: "Mathematics (3)",
      code: "MTH 101",
      creditHours: 3,
      gpa: 0,
      gpaLetter: 'NF',
    ),
    Course(
      name: "Mathematics (4)",
      code: "MTH 102",
      creditHours: 3,
      gpa: 0,
      gpaLetter: 'NF',
    ),
  ];

  final List<Course> majorRequirementCoursesList = [
    Course(
      name: "Logic Design (1)",
      code: "EEC 112",
      creditHours: 3,
      gpa: 0,
      gpaLetter: 'NF',
    ),
    Course(
      name: "Computer Engineering (1)",
      code: "EEC 113",
      creditHours: 2,
      gpa: 0,
      gpaLetter: 'NF',
    ),
    Course(
      name: "Signal Analysis and Systems",
      code: "EEC 115",
      creditHours: 3,
      gpa: 0,
      gpaLetter: 'NF',
    ),
    Course(
      name: "Electric Circuits (2)",
      code: "EEC 121",
      creditHours: 3,
      gpa: 0,
      gpaLetter: 'NF',
    ),
    Course(
      name: "Electrical Measurements",
      code: "EEC 123",
      creditHours: 3,
      gpa: 0,
      gpaLetter: 'NF',
    ),
    Course(
      name: "Computer Engineering (2)",
      code: "EEC 124",
      creditHours: 2,
      gpa: 0,
      gpaLetter: 'NF',
    ),
    Course(
      name: "Control Systems (1)",
      code: "EEC 125",
      creditHours: 3,
      gpa: 0,
      gpaLetter: 'NF',
    ),
    Course(
      name: "Electronics (2)",
      code: "EEC 141",
      creditHours: 2,
      gpa: 0,
      gpaLetter: 'NF',
    ),
    Course(
      name: "Logic Design (2)",
      code: "EEC 142",
      creditHours: 2,
      gpa: 0,
      gpaLetter: 'NF',
    ),
    Course(
      name: "Electronics (3)",
      code: "EEC 151",
      creditHours: 2,
      gpa: 0,
      gpaLetter: 'NF',
    ),
    Course(
      name: "Electromagnetic Fields (1)",
      code: "EEC 152",
      creditHours: 3,
      gpa: 0,
      gpaLetter: 'NF',
    ),
    Course(
      name: "Electrical Machines",
      code: "EEC 154",
      creditHours: 2,
      gpa: 0,
      gpaLetter: 'NF',
    ),
    Course(
      name: "Electromagnetic Fields (2)",
      code: "EEC 211",
      creditHours: 3,
      gpa: 0,
      gpaLetter: 'NF',
    ),
    Course(
      name: "Control Systems (2)",
      code: "EEC 212",
      creditHours: 3,
      gpa: 0,
      gpaLetter: 'NF',
    ),
    Course(
      name: "Communications (1)",
      code: "EEC 213",
      creditHours: 3,
      gpa: 0,
      gpaLetter: 'NF',
    ),
    Course(
      name: "Microprocessors",
      code: "EEC 214",
      creditHours: 4,
      gpa: 0,
      gpaLetter: 'NF',
    ),
    Course(
      name: "Computer Architecture and Organization",
      code: "EEC 216",
      creditHours: 4,
      gpa: 0,
      gpaLetter: 'NF',
    ),
    Course(
      name: "Microwave Engineering",
      code: "EEC 222",
      creditHours: 3,
      gpa: 0,
      gpaLetter: 'NF',
    ),
    Course(
      name: "Communications (2)",
      code: "EEC 223",
      creditHours: 3,
      gpa: 0,
      gpaLetter: 'NF',
    ),
    Course(
      name: "Data Communication and Computer Networks",
      code: "EEC 224",
      creditHours: 3,
      gpa: 0,
      gpaLetter: 'NF',
    ),
    Course(
      name: "Digital Signal Processing (1)",
      code: "EEC 225",
      creditHours: 3,
      gpa: 0,
      gpaLetter: 'NF',
    ),
    Course(
      name: "Antennas",
      code: "EEC 241",
      creditHours: 3,
      gpa: 0,
      gpaLetter: 'NF',
    ),
    Course(
      name: "Communications (3)",
      code: "EEC 242",
      creditHours: 3,
      gpa: 0,
      gpaLetter: 'NF',
    ),
    Course(
      name: "Communications (4)",
      code: "EEC 251",
      creditHours: 3,
      gpa: 0,
      gpaLetter: 'NF',
    ),
    Course(
      name: "Industrial Process Control",
      code: "EEC 255",
      creditHours: 2,
      gpa: 0,
      gpaLetter: 'NF',
    ),
    Course(
      name: "Bachelor Project",
      code: "EEC 290",
      creditHours: 3,
      gpa: 0,
      gpaLetter: 'NF',
    ),
    Course(
      name: "Field Training (3)",
      code: "FTR 231",
      creditHours: 3,
      gpa: 0,
      gpaLetter: 'NF',
    ),
    Course(
      name: "Field Training (4)",
      code: "FTR 261",
      creditHours: 3,
      gpa: 0,
      gpaLetter: 'NF',
    ),
  ];

  // One Course (List D)
  final List<Course> economicOptCourses = [
    Course(
      name: "Introduction To Accounting",
      code: "HUM 201",
      creditHours: 2,
      gpa: 0,
      gpaLetter: 'NF',
    ),
    Course(
      name: "English Literature",
      code: "HUM 202",
      creditHours: 2,
      gpa: 0,
      gpaLetter: 'NF',
    ),
    Course(
      name: "Trade Law",
      code: "HUM 203",
      creditHours: 2,
      gpa: 0,
      gpaLetter: 'NF',
    ),
    Course(
      name: "Entrepreneurship",
      code: "HUM 206",
      creditHours: 2,
      gpa: 0,
      gpaLetter: 'NF',
    ),
    Course(
      name: "Scientific Thinking",
      code: "HUM 207",
      creditHours: 2,
      gpa: 0,
      gpaLetter: 'NF',
    ),
    Course(
      name: "Business Administration",
      code: "HUM 208",
      creditHours: 2,
      gpa: 0,
      gpaLetter: 'NF',
    ),
  ];

  // Two Courses (List E)
  final List<Course> cultureOptCourses = [
    Course(
      name: "Introduction To The History of Civilizations",
      code: "HUM 101",
      creditHours: 2,
      gpa: 0,
      gpaLetter: 'NF',
    ),
    Course(
      name: "Recent Egypt's History",
      code: "HUM 102",
      creditHours: 2,
      gpa: 0,
      gpaLetter: 'NF',
    ),
    Course(
      name: "Arab & Islamic Civilization",
      code: "HUM 103",
      creditHours: 2,
      gpa: 0,
      gpaLetter: 'NF',
    ),
    Course(
      name: "Literary Appreciation",
      code: "HUM 104",
      creditHours: 2,
      gpa: 0,
      gpaLetter: 'NF',
    ),
    Course(
      name: "Music Appreciation",
      code: "HUM 105",
      creditHours: 2,
      gpa: 0,
      gpaLetter: 'NF',
    ),
    Course(
      name: "Heritage Of Egyptian Literature",
      code: "HUM 106",
      creditHours: 2,
      gpa: 0,
      gpaLetter: 'NF',
    ),
    Course(
      name: "Trends in Contemporary Arts",
      code: "HUM 107",
      creditHours: 2,
      gpa: 0,
      gpaLetter: 'NF',
    ),
    Course(
      name: "French Language",
      code: "LNG 101",
      creditHours: 2,
      gpa: 0,
      gpaLetter: 'NF',
    ),
    Course(
      name: "German Language",
      code: "LNG 102",
      creditHours: 2,
      gpa: 0,
      gpaLetter: 'NF',
    ),
  ];

  // Three Courses (List F')
  final List<Course> introCourses = [
    Course(
      name: "Principles of Construction & Building Engineering",
      code: "CIV 101",
      creditHours: 2,
      gpa: 0,
      gpaLetter: 'NF',
    ),
    Course(
      name: "Arts & Architecture",
      code: "ARE 101",
      creditHours: 2,
      gpa: 0,
      gpaLetter: 'NF',
    ),
    Course(
      name: "Principles of Electrical Engineering",
      code: "EEC 101",
      creditHours: 2,
      gpa: 0,
      gpaLetter: 'NF',
    ),
    Course(
      name: "Principles of Electronic Engineering",
      code: "EEC 102",
      creditHours: 2,
      gpa: 0,
      gpaLetter: 'NF',
    ),
    Course(
      name: "Principles of Electric Machines",
      code: "EEC 103",
      creditHours: 2,
      gpa: 0,
      gpaLetter: 'NF',
    ),
    Course(
      name: "Principles of Design & Manufacturing Engineering",
      code: "ENG 103",
      creditHours: 2,
      gpa: 0,
      gpaLetter: 'NF',
    ),
    Course(
      name: "Principles of Mechanical Power Engineering",
      code: "ENG 104",
      creditHours: 2,
      gpa: 0,
      gpaLetter: 'NF',
    ),
    Course(
      name: "Principles of Mechatronics Engineering",
      code: "MTE 101",
      creditHours: 2,
      gpa: 0,
      gpaLetter: 'NF',
    ),
    Course(
      name: "Principles of Biomedical Engineering",
      code: "MDE 101",
      creditHours: 2,
      gpa: 0,
      gpaLetter: 'NF',
    ),
  ];

  // Three Courses (List G)
  final List<Course> mathOptCourses = [
    Course(
      name: "Numerical Methods",
      code: "MTH 103",
      creditHours: 3,
      gpa: 0,
      gpaLetter: 'NF',
    ),
    Course(
      name: "Mathematical Analysis",
      code: "MTH 104",
      creditHours: 3,
      gpa: 0,
      gpaLetter: 'NF',
    ),
    Course(
      name: "Advanced Calculus",
      code: "MTH 206",
      creditHours: 3,
      gpa: 0,
      gpaLetter: 'NF',
    ),
    Course(
      name: "Selected Topics in Mathematics",
      code: "MTH 210",
      creditHours: 3,
      gpa: 0,
      gpaLetter: 'NF',
    ),
    Course(
      name: "Quantum Physics",
      code: "PHY 111",
      creditHours: 3,
      gpa: 0,
      gpaLetter: 'NF',
    ),
  ];

  // Four Courses (List H)
  final List<Course> departmentOptCourses = [
    Course(
      name: "Artificial Intelligence",
      code: "EEC 271",
      creditHours: 3,
      gpa: 0,
      gpaLetter: 'NF',
    ),
    Course(
      name: "Introduction to Medical Electronics",
      code: "EEC 272",
      creditHours: 3,
      gpa: 0,
      gpaLetter: 'NF',
    ),
    Course(
      name: "Advanced Optical Fiber Communications",
      code: "EEC 273",
      creditHours: 3,
      gpa: 0,
      gpaLetter: 'NF',
    ),
    Course(
      name: "Advanced Mobile Communication",
      code: "EEC 274",
      creditHours: 3,
      gpa: 0,
      gpaLetter: 'NF',
    ),
    Course(
      name: "Advanced Control Engineering",
      code: "EEC 276",
      creditHours: 3,
      gpa: 0,
      gpaLetter: 'NF',
    ),
    Course(
      name: "Wireless Network & Applications",
      code: "EEC 277",
      creditHours: 3,
      gpa: 0,
      gpaLetter: 'NF',
    ),
    Course(
      name: "Power Electronics",
      code: "EEC 278",
      creditHours: 3,
      gpa: 0,
      gpaLetter: 'NF',
    ),
    Course(
      name: "Introduction to Mechatronics",
      code: "EEC 279",
      creditHours: 3,
      gpa: 0,
      gpaLetter: 'NF',
    ),
    Course(
      name: "Communication Security Systems",
      code: "EEC 280",
      creditHours: 3,
      gpa: 0,
      gpaLetter: 'NF',
    ),
    Course(
      name: "Advanced Electronics",
      code: "EEC 281",
      creditHours: 3,
      gpa: 0,
      gpaLetter: 'NF',
    ),
    Course(
      name: "Electronics (4)",
      code: "EEC 282",
      creditHours: 3,
      gpa: 0,
      gpaLetter: 'NF',
    ),
    Course(
      name: "Electronics Instrumentation",
      code: "EEC 283",
      creditHours: 3,
      gpa: 0,
      gpaLetter: 'NF',
    ),
    Course(
      name: "Advanced Satellite Communication",
      code: "EEC 284",
      creditHours: 3,
      gpa: 0,
      gpaLetter: 'NF',
    ),
    Course(
      name: "Computer Engineering (3)",
      code: "EEC 285",
      creditHours: 3,
      gpa: 0,
      gpaLetter: 'NF',
    ),
    Course(
      name: "Neuro Fuzzy Control",
      code: "EEC 286",
      creditHours: 3,
      gpa: 0,
      gpaLetter: 'NF',
    ),
    Course(
      name: "Selected Topics in Medical Electronics",
      code: "EEC 287",
      creditHours: 3,
      gpa: 0,
      gpaLetter: 'NF',
    ),
    Course(
      name: "Digital Signal Processing (2)",
      code: "EEC 288",
      creditHours: 3,
      gpa: 0,
      gpaLetter: 'NF',
    ),
    Course(
      name: "Radar and Electronic warfare Systems",
      code: "EEC 289",
      creditHours: 3,
      gpa: 0,
      gpaLetter: 'NF',
    ),
  ];

  Map<Map<String, int>, List<Course>> get allCoursesMap => {
    {"Lista A": -1}: generalCoursesList,
    {"List B": -1}: requirementCoursesList,
    {"List C": -1}: majorRequirementCoursesList,
    {"List D": 1}: economicOptCourses,
    {"List E": 2}: cultureOptCourses,
    {"List F": 3}: introCourses,
    {"List G": 3}: mathOptCourses,
    {"List H": 4}: departmentOptCourses,
  };

  List<Course> get allCoursesList => [
    ...generalCoursesList,
    ...requirementCoursesList,
    ...majorRequirementCoursesList,
    ...economicOptCourses,
    ...cultureOptCourses,
    ...introCourses,
    ...mathOptCourses,
    ...departmentOptCourses,
  ];

  /*
  اختيارى س  -> cultureOptCourses
  اختيارى ب  -> introCourses
  اختيارى أ  -> mathOptCourses
  اختيارى د  -> economicOptCourses
  اختيارى ى  ->  departmentOptCourses

  */

  static  Map<String, List<Course>> get electivePatterns {
    return {
      'HUM (1)': Electrical().cultureOptCourses, // Culture Elective (Choose 1) - List E
      'HUM (2)': Electrical().cultureOptCourses, // Culture Elective (Choose 1) - List E
      'HUM (3)': Electrical().economicOptCourses, // Economic Elective (Choose 1) - List D
      'MTH (1)': Electrical().mathOptCourses, // Math Elective (Choose 1) - List G
      'MTH (2)': Electrical().mathOptCourses, // Math Elective (Choose 1) - List G
      'MTH (3)': Electrical().mathOptCourses, // Math Elective (Choose 1) - List G
      'EEC (1)': Electrical().introCourses, // Intro Elective (Choose 1) - List F
      'EEC (2)': Electrical().introCourses, // Intro Elective (Choose 1) - List F
      'EEC (3)':Electrical(). introCourses, // Intro Elective (Choose 1) - List F
      'ELEC (1)':
          Electrical().departmentOptCourses, // Department Elective (Choose 1) - List H
      'ELEC (2)':
          Electrical().departmentOptCourses, // Department Elective (Choose 1) - List H
      'ELEC (3)':
          Electrical().departmentOptCourses, // Department Elective (Choose 1) - List H
      'ELEC (4)':
          Electrical().departmentOptCourses, // Department Elective (Choose 1) - List H
    };
  }

  static Map<String, List<Course>> get departmentTree => {
    "prep": [
      Course(
        name: "Engineering Chemistry",
        code: "CHM 001",
        creditHours: 3,
        gpa: 0,
        gpaLetter: 'NF',
      ),
      Course(
        name: "Computer Skills",
        code: "CSC 001",
        creditHours: 0,
        gpa: 0,
        gpaLetter: 'NF',
      ),
      Course(
        name: "Engineering Drawing & Projection (1)",
        code: "ENG 003",
        creditHours: 2,
        gpa: 0,
        gpaLetter: 'NF',
      ),
      Course(
        name: "Engineering Drawing & Projection (2)",
        code: "ENG 004",
        creditHours: 2,
        gpa: 0,
        gpaLetter: 'NF',
      ),
      Course(
        name: "Principles of Production Technology & Workshop",
        code: "ENG 005",
        creditHours: 3,
        gpa: 0,
        gpaLetter: 'NF',
      ),
      Course(
        name: "History of Engineering & Technology",
        code: "ENG 006",
        creditHours: 1,
        gpa: 0,
        gpaLetter: 'NF',
      ),
      Course(
        name: "Engineering Mechanics (1)",
        code: "ENG 001",
        creditHours: 2,
        gpa: 0,
        gpaLetter: 'NF',
      ),
      Course(
        name: "Engineering Mechanics (2)",
        code: "ENG 002",
        creditHours: 2,
        gpa: 0,
        gpaLetter: 'NF',
      ),
      Course(
        name: "Introduction to Field Training",
        code: "FTR 031",
        creditHours: 3,
        gpa: 0,
        gpaLetter: 'NF',
      ),
      Course(
        name: "English Language (1)",
        code: "LNG 001",
        creditHours: 2,
        gpa: 0,
        gpaLetter: 'NF',
      ),
      Course(
        name: "Mathematics (1)",
        code: "MTH 001",
        creditHours: 3,
        gpa: 0,
        gpaLetter: 'NF',
      ),
      Course(
        name: "Physical Education & Activities (1)",
        code: "PHE 001",
        creditHours: 0,
        gpa: 0,
        gpaLetter: 'NF',
      ),
      Course(
        name: "Physics (1)",
        code: "PHY 001",
        creditHours: 3,
        gpa: 0,
        gpaLetter: 'NF',
      ),
      Course(
        name: "Physics (2)",
        code: "PHY 002",
        creditHours: 3,
        gpa: 0,
        gpaLetter: 'NF',
      ),
      Course(
        name: "Mathematics (2)",
        code: "MTH 002",
        creditHours: 3,
        gpa: 0,
        gpaLetter: 'NF',
      ),
      Course(
        name: "Arabic Language",
        code: "LNG 003",
        creditHours: 2,
        gpa: 0,
        gpaLetter: 'NF',
      ),
      Course(
        name: "English Language (2)",
        code: "LNG 002",
        creditHours: 2,
        gpa: 0,
        gpaLetter: 'NF',
      ),
    ],
    "year1": [
      Course(
        name: "Logic Design (1)",
        code: "EEC 112",
        creditHours: 3,
        gpa: 0,
        gpaLetter: 'NF',
      ),
      Course(
        name: "Computer Engineering (1)",
        code: "EEC 113",
        creditHours: 2,
        gpa: 0,
        gpaLetter: 'NF',
      ),
      Course(
        name: "Mathematics (3)",
        code: "MTH 101",
        creditHours: 3,
        gpa: 0,
        gpaLetter: 'NF',
      ),
      Course(
        name: "Math Elective (Choose 1)",
        code: "MTH (1)",
        creditHours: 3,
        gpa: 0,
        gpaLetter: 'NF',
      ),
      Course(
        name: "Intro Elective (Choose 1)",
        code: "EEC (1)",
        creditHours: 2,
        gpa: 0,
        gpaLetter: 'NF',
      ),
      Course(
        name: "Intro Elective (Choose 1)",
        code: "EEC (2)",
        creditHours: 2,
        gpa: 0,
        gpaLetter: 'NF',
      ),
      Course(
        name: "Intro Elective (Choose 1)",
        code: "EEC (3)",
        creditHours: 2,
        gpa: 0,
        gpaLetter: 'NF',
      ),
      Course(
        name: "Physical Education & Activities (2)",
        code: "PHE 101",
        creditHours: 0,
        gpa: 0,
        gpaLetter: 'NF',
      ),
      Course(
        name: "Electric Circuits (2)",
        code: "EEC 121",
        creditHours: 3,
        gpa: 0,
        gpaLetter: 'NF',
      ),
      Course(
        name: "Electrical Measurements",
        code: "EEC 123",
        creditHours: 3,
        gpa: 0,
        gpaLetter: 'NF',
      ),
      Course(
        name: "Computer Engineering (2)",
        code: "EEC 124",
        creditHours: 2,
        gpa: 0,
        gpaLetter: 'NF',
      ),
      Course(
        name: "Mathematics (4)",
        code: "MTH 102",
        creditHours: 3,
        gpa: 0,
        gpaLetter: 'NF',
      ),
      Course(
        name: "Culture Elective (Choose 1)",
        code: "HUM (1)",
        creditHours: 2,
        gpa: 0,
        gpaLetter: 'NF',
      ),
      Course(
        name: "Monitoring & Quality Control Systems",
        code: "MNG 101",
        creditHours: 1,
        gpa: 0,
        gpaLetter: 'NF',
      ),
      Course(
        name: "Engineering Economics",
        code: "MNG 102",
        creditHours: 2,
        gpa: 0,
        gpaLetter: 'NF',
      ),
      Course(
        name: "Field Training (1)",
        code: "FTR 131",
        creditHours: 3,
        gpa: 0,
        gpaLetter: 'NF',
      ),
    ],
    "year2": [
      Course(
        name: "Electronics (2)",
        code: "EEC 141",
        creditHours: 2,
        gpa: 0,
        gpaLetter: 'NF',
      ),
      Course(
        name: "Logic Design (2)",
        code: "EEC 142",
        creditHours: 2,
        gpa: 0,
        gpaLetter: 'NF',
      ),
      Course(
        name: "Signal Analysis and Systems",
        code: "EEC 115",
        creditHours: 3,
        gpa: 0,
        gpaLetter: 'NF',
      ),
      Course(
        name: "Math Elective (Choose 1)",
        code: "MTH (2)",
        creditHours: 3,
        gpa: 0,
        gpaLetter: 'NF',
      ),
      Course(
        name: "Technical Report Writing",
        code: "MNG 103",
        creditHours: 2,
        gpa: 0,
        gpaLetter: 'NF',
      ),
      Course(
        name: "Communication & Presentation Skills",
        code: "HUM 108",
        creditHours: 2,
        gpa: 0,
        gpaLetter: 'NF',
      ),
      Course(
        name: "Analysis & Research Skills",
        code: "HUM 109",
        creditHours: 2,
        gpa: 0,
        gpaLetter: 'NF',
      ),
      Course(
        name: "Electronics (3)",
        code: "EEC 151",
        creditHours: 2,
        gpa: 0,
        gpaLetter: 'NF',
      ),
      Course(
        name: "Electromagnetic Fields (1)",
        code: "EEC 152",
        creditHours: 3,
        gpa: 0,
        gpaLetter: 'NF',
      ),
      Course(
        name: "Electrical Machines",
        code: "EEC 154",
        creditHours: 2,
        gpa: 0,
        gpaLetter: 'NF',
      ),
      Course(
        name: "Control Systems (1)",
        code: "EEC 125",
        creditHours: 3,
        gpa: 0,
        gpaLetter: 'NF',
      ),
      Course(
        name: "Statistics & Probability Theory",
        code: "MTH 105",
        creditHours: 3,
        gpa: 0,
        gpaLetter: 'NF',
      ),
      Course(
        name: "Culture Elective (Choose 1)",
        code: "HUM (2)",
        creditHours: 2,
        gpa: 0,
        gpaLetter: 'NF',
      ),
      Course(
        name: "Math Elective (Choose 1)",
        code: "MTH (3)",
        creditHours: 3,
        gpa: 0,
        gpaLetter: 'NF',
      ),
      Course(
        name: "Field Training (2)",
        code: "FTR 161",
        creditHours: 3,
        gpa: 0,
        gpaLetter: 'NF',
      ),
    ],
    "year3": [
      Course(
        name: "Electromagnetic Fields (2)",
        code: "EEC 211",
        creditHours: 3,
        gpa: 0,
        gpaLetter: 'NF',
      ),
      Course(
        name: "Industrial Process Control",
        code: "EEC 255",
        creditHours: 2,
        gpa: 0,
        gpaLetter: 'NF',
      ),
      Course(
        name: "Control Systems (2)",
        code: "EEC 212",
        creditHours: 3,
        gpa: 0,
        gpaLetter: 'NF',
      ),
      Course(
        name: "Communications (1)",
        code: "EEC 213",
        creditHours: 3,
        gpa: 0,
        gpaLetter: 'NF',
      ),
      Course(
        name: "Project Management",
        code: "MNG 201",
        creditHours: 2,
        gpa: 0,
        gpaLetter: 'NF',
      ),
      Course(
        name: "Department Elective (Choose 1)",
        code: "ELEC (1)",
        creditHours: 3,
        gpa: 0,
        gpaLetter: 'NF',
      ),
      Course(
        name: "Digital Signal Processing (1)",
        code: "EEC 225",
        creditHours: 3,
        gpa: 0,
        gpaLetter: 'NF',
      ),
      Course(
        name: "Communications (2)",
        code: "EEC 223",
        creditHours: 3,
        gpa: 0,
        gpaLetter: 'NF',
      ),
      Course(
        name: "Data Communication and Computer Networks",
        code: "EEC 224",
        creditHours: 3,
        gpa: 0,
        gpaLetter: 'NF',
      ),
      Course(
        name: "Microwave Engineering",
        code: "EEC 222",
        creditHours: 3,
        gpa: 0,
        gpaLetter: 'NF',
      ),
      Course(
        name: "Computer Architecture and Organization",
        code: "EEC 216",
        creditHours: 4,
        gpa: 0,
        gpaLetter: 'NF',
      ),
      Course(
        name: "Department Elective (Choose 1)",
        code: "ELEC (2)",
        creditHours: 3,
        gpa: 0,
        gpaLetter: 'NF',
      ),
      Course(
        name: "Field Training (3)",
        code: "FTR 231",
        creditHours: 3,
        gpa: 0,
        gpaLetter: 'NF',
      ),
    ],
    "year4": [
      Course(
        name: "Communications (3)",
        code: "EEC 242",
        creditHours: 3,
        gpa: 0,
        gpaLetter: 'NF',
      ),
      Course(
        name: "Antennas",
        code: "EEC 241",
        creditHours: 3,
        gpa: 0,
        gpaLetter: 'NF',
      ),
      Course(
        name: "Microprocessors",
        code: "EEC 214",
        creditHours: 4,
        gpa: 0,
        gpaLetter: 'NF',
      ),
      Course(
        name: "Environmental Impact of Projects",
        code: "MNG 202",
        creditHours: 1,
        gpa: 0,
        gpaLetter: 'NF',
      ),
      Course(
        name: "Professional Ethics",
        code: "MNG 203",
        creditHours: 1,
        gpa: 0,
        gpaLetter: 'NF',
      ),
      Course(
        name: "Physical Education & Activities (3)",
        code: "PHE 201",
        creditHours: 1,
        gpa: 0,
        gpaLetter: 'NF',
      ),
      Course(
        name: "Human Rights",
        code: "HUM 205",
        creditHours: 1,
        gpa: 0,
        gpaLetter: 'NF',
      ),
      Course(
        name: "Bachelor Project",
        code: "EEC 290",
        creditHours: 3,
        gpa: 0,
        gpaLetter: 'NF',
      ),
      Course(
        name: "Communications (4)",
        code: "EEC 251",
        creditHours: 3,
        gpa: 0,
        gpaLetter: 'NF',
      ),
      Course(
        name: "Department Elective (Choose 1)",
        code: "ELEC (3)",
        creditHours: 3,
        gpa: 0,
        gpaLetter: 'NF',
      ),
      Course(
        name: "Department Elective (Choose 1)",
        code: "ELEC (4)",
        creditHours: 3,
        gpa: 0,
        gpaLetter: 'NF',
      ),
      Course(
        name: "Economic Elective (Choose 1)",
        code: "HUM (3)",
        creditHours: 2,
        gpa: 0,
        gpaLetter: 'NF',
      ),
      Course(
        name: "Principles of Negotiation",
        code: "HUM 204",
        creditHours: 2,
        gpa: 0,
        gpaLetter: 'NF',
      ),
      Course(
        name: "Field Training (4)",
        code: "FTR 261",
        creditHours: 3,
        gpa: 0,
        gpaLetter: 'NF',
      ),
    ],
  };

}
